version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db-fresh-market
    environment:
      MYSQL_ROOT_PASSWORD: fresh_market
      MYSQL_DATABASE: fresh_market
      MYSQL_USER: db_user
      MYSQL_PASSWORD: fresh_market
    ports:
      - "6034:3306"
    volumes:
      - ./data/db:/var/lib/mysql
